config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('message-panel/', include('email_sender.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

email_sender/urls.py
from django.urls import path

from . import views

app_name = 'email_sender'

urlpatterns = [
    path('', views.MessagePanelView.as_view(), name='msg_panel'),
    path('<int:pk>/', views.MessageDetailView.as_view(), name='msg_detail'),
    path('send/', views.send_and_save_mgs_view, name='msg_panel_send'),
    path('filter-recipients/', views.filter_recipients_view, name='filter_recipients'),
]

email_sender/forms/msg_record_forms.py
from django import forms
from django.db import IntegrityError
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth import get_user_model

from ..models import Recipient, MsgRecord, MsgRecordImage, MsgRecordFile


class MsgRecordForm(forms.ModelForm):
    recipients = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = MsgRecord
        exclude = ('is_sent',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs['class'] = 'w-100 w-sm-50 '

    def clean_recipients(self):
        # Clean the raw input from 'recipients', removing spaces, newlines, and carriage returns
        recipients_data = self.cleaned_data['recipients'].replace(' ', '').replace('\r', '').replace('\n', '')

        # Split input by commas and store as a set to remove duplicates
        entries = set(recipients_data.split(','))
        recipients_list = []
        entries.discard('')  # Remove empty entries

        # Ensure there are valid entries, otherwise return an error
        if entries:
            user_model = get_user_model()

            for entry in entries:
                try:
                    try:
                        # Check if entry is in 'username:email' format by attempting to split on ':'
                        username, email = entry.split(':')
                        try:
                            # Get the user by the provided username
                            user = user_model.objects.get(username=username)

                            # Validate the email format
                            validate_email(email)

                            try:
                                # Try to get the recipient by email
                                recipient = Recipient.objects.get(email=email)

                                # If recipient exists but has no user, assign the user to the recipient
                                if not recipient.user:
                                    recipient.user = user
                                    recipient.save()

                                # If recipient exists with a different user, raise an error
                                elif recipient.user != user:
                                    self.add_error(
                                        'recipients',
                                        _(f'The user for email "{email}" is "{recipient.user}", but you entered "{user}".')
                                    )

                            except Recipient.DoesNotExist:
                                # If recipient doesn't exist, create a new recipient with the user and email
                                try:
                                    recipient = Recipient.objects.create(user=user, email=email)

                                except IntegrityError:
                                    # If there's an IntegrityError (user already exists), get the recipient by user
                                    recipient = Recipient.objects.get(user=user)

                                    # Update the recipient's email if necessary
                                    if user.email == email:
                                        recipient.email = email
                                        recipient.save()

                                    # If email doesn't match, raise an error
                                    else:
                                        self.add_error(
                                            'recipients',
                                            _(f'The email for user "{user}" is "{recipient.email}", but you entered "{email}".')
                                        )

                            # Add the recipient to the list
                            recipients_list.append(recipient)

                        # Handle case where the username does not exist
                        except user_model.DoesNotExist:
                            self.add_error('recipients', _(f'username "{username}" is invalid.'))

                    except ValueError:
                        # If there's no username, assume it's an email-only entry
                        email = entry
                        validate_email(email)  # Validate the email format

                        # Get or create recipient by email
                        recipient, created = Recipient.objects.get_or_create(email=email)
                        # Add the recipient to the list
                        recipients_list.append(recipient)

                # Handle any validation errors
                except ValidationError as e:
                    self.add_error('recipients', e)

        else:
            # Raise error if no valid entries
            self.add_error('recipients', _('The format is not correct'))

        return recipients_list

    def validate_files_size(self, request_files_values):
        sum_size_files = sum([file.size / (1024 * 1024) for file in request_files_values])
        if sum_size_files > 25:
            self.add_error(None,
                           _(f'The maximum of files with images must be 25 MB. total size: {sum_size_files:.2f} MB,'
                             f' also you can add Google Drive link in the message.'))


class MsgRecordImageForm(forms.ModelForm):
    img = forms.ImageField(label='', required=False)

    class Meta:
        model = MsgRecordImage
        fields = ('img',)

    def clean_img(self):
        img = self.cleaned_data.get('img')
        if img is False:
            return None  # Allow the field to be cleared
        return img


class MsgRecordFileForm(forms.ModelForm):
    file = forms.FileField(label='', required=False)

    class Meta:
        model = MsgRecordFile
        fields = ('file',)

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if file is False:
            return None  # Allow the field to be cleared
        return file

email_sender/views.py
import json

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.http import JsonResponse
from django.db.models import F

from .models import MsgRecord, MsgRecordImage, MsgRecordFile, Recipient
from .forms import MsgRecordForm
from .mixins import JSONResponseMixin
from .utils import DateTimeEncoder
from .filters import RecipientFilter


class MessagePanelView(LoginRequiredMixin, generic.ListView):
    model = MsgRecord
    paginate_by = 10
    template_name = 'email_sender/msg_panel_template.html'
    context_object_name = 'msg_list'
    queryset = MsgRecord.objects.filter(is_sent=True)

    def get_queryset(self):
        queryset = super().get_queryset()

        q = self.request.GET.get('q')
        if q:
            queryset = queryset.filter(subject__icontains=q).distinct()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.is_ajax():
            context['msg_record_img_formset'] = MsgRecordImage.get_img_formset()
            context['msg_record_file_formset'] = MsgRecordFile.get_file_formset()
            context['msg_record_form'] = MsgRecordForm()
            context['filter_recipient_form'] = RecipientFilter().form

        return context

    def is_ajax(self):
        return self.request.headers.get('x-requested-with') == 'XMLHttpRequest'

    def get(self, request, *args, **kwargs):
        if self.is_ajax():
            self.object_list = self.get_queryset()
            context = self.get_context_data(**kwargs)
            page_obj = context['page_obj']
            msg_query = context['msg_list'].values('id', 'subject', 'datetime_created')

            msg_list = [{**msg_obj, 'url': MsgRecord.objects.get(id=msg_obj['id']).get_absolute_url()} for msg_obj in
                        msg_query]

            return JsonResponse({
                'msg_list': json.dumps(msg_list, cls=DateTimeEncoder, date_format='%Y/%m/%d at %H:%M'),
                'page': page_obj.number,
                'total_pages': page_obj.paginator.num_pages,
                'has_previous': page_obj.has_previous(),
                'previous_page_number': page_obj.previous_page_number() if page_obj.has_previous() else None,
                'has_next': page_obj.has_next(),
                'next_page_number': page_obj.next_page_number() if page_obj.has_next() else None
            })

        return super().get(request, *args, **kwargs)


@login_required
@require_POST
def send_and_save_mgs_view(request):
    json_mixin_obj = JSONResponseMixin()

    request_post, request_files = request.POST, request.FILES

    msg_form = MsgRecordForm(request_post)
    msg_img_formset = MsgRecordImage.get_img_formset(data=request_post, files=request_files)
    msg_file_formset = MsgRecordFile.get_file_formset(data=request_post, files=request_files)

    is_msg_send = MsgRecord.process_message(request_files.values(), msg_form, msg_img_formset, msg_file_formset)

    if is_msg_send:
        messages.success(request, _('Message successfully sent.'))
        return json_mixin_obj.render_to_json_response({'message': 'success'})

    # Handle form and formset errors
    response_data = {
        'msg_form': json_mixin_obj.ajax_response_form(msg_form),
        'msg_img_formset': [json_mixin_obj.ajax_response_form(f) for f in msg_img_formset.forms],
        'msg_file_formset': [json_mixin_obj.ajax_response_form(f) for f in msg_file_formset.forms],
    }

    return json_mixin_obj.render_to_json_response(response_data, status=400)


class MessageDetailView(generic.DetailView):
    model = MsgRecord
    template_name = 'email_sender/msg_detail.html'
    context_object_name = 'msg_obj'
    queryset = model.objects.prefetch_related('images', 'files')


@login_required
@require_GET
def filter_recipients_view(request):
    json_mixin_obj = JSONResponseMixin()
    filter_recipients = RecipientFilter(request.GET, Recipient.objects.all())
    recipients_data = filter_recipients.qs.values('email', username=F('user__username'))
    return json_mixin_obj.render_to_json_response({'recipients': json.dumps(list(recipients_data))})

email_sender/templates/email_sender/_msg_sent_list.html
<div class="messages">
    {% for message in msg_list %}
        <p class="messages__item">
            <a href="{{ message.get_absolute_url }}" class="messages__item__link">{{ message.pk }}: {{ message.subject }} {{ message.datetime_created|date:"Y/m/d \a\t H:i" }}</a>
        </p>
    {% endfor %}
</div>

email_sender/templates/email_sender/_pagination.html
<nav aria-label="{{ area_label }} Pagination">
    <ul id="{{ pagination_id }}" class="pagination-cst">
        {% if page_obj.paginator.num_pages > 1 %}
            {% if page_obj.has_previous %}
                <li class="page-item-cst">
                    <a class="page-link-cst" href="?page=1" aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item-cst">
                    <a class="page-link-cst" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&lsaquo;</span>
                    </a>
                </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
                {% if page == page_obj.number %}
                    <li class="page-item-cst active"><span class="page-link-cst">{{ page }}</span></li>
                {% else %}
                    <li class="page-item-cst"><a class="page-link-cst" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item-cst">
                    <a class="page-link-cst" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&rsaquo;</span>
                    </a>
                </li>
                <li class="page-item-cst">
                    <a class="page-link-cst" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        {% endif %}
    </ul>
</nav>

email_sender/templates/email_sender/msg_detail.html
{% extends '_base.html' %}

{% load email_sender_filters %}

{% block title %}{{ msg_obj.subject }}{% endblock title %}

{% block content %}

    <p class="mb-3">Subject: {{ msg_obj.subject }}</p>

    <p>Message</p>
    <div class="border rounded-4 p-3 mb-4">{{ msg_obj.message|safe }}</div>

    <div class="mb-4">
        <p class="m-1">Images</p>
        {% if msg_obj.images.all %}
            <div class="d-flex flex-wrap justify-content-center gap-3">
                {% for img_obj in msg_obj.images.all %}
                    <img src="{{ img_obj.img.url }}" alt="Image" class="img-thumbnail w-100 w-md-75 w-lg-25">
                {% endfor %}
            </div>
        {% else %}
            <p class="text-muted ps-4">No images available</p>
        {% endif %}
    </div>

    <div class="mb-4">
        <p class="m-1">Files</p>
        {% if msg_obj.files.all %}
            <ul class="list-unstyled">
                {% for file_obj in msg_obj.files.all %}
                    <li>
                        <a href="{{ file_obj.file.url }}" target="_blank" class="text-decoration-none">
                            <i class="fa-solid fa-download me-2"></i>{{ file_obj.file|filename }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="text-muted ps-4">No files available</p>
        {% endif %}
    </div>

    <div class="mb-4">
        <p>Recipients</p>
        <p class="recipient-list max-h-150 border rounded-4 p-2">
            {% for recipient in msg_obj.recipients.all %}
                <span class="recipient-item bg-secondary">{{ recipient.email }}</span>
            {% endfor %}
        </p>
    </div>

    <div class="text-muted">
        <p><strong>Created:</strong> {{ msg_obj.datetime_created }}</p>
        <p><strong>Updated:</strong> {{ msg_obj.datetime_updated }}</p>
    </div>

{% endblock content %}

email_sender/templates/email_sender/msg_panel_template.html
{% extends '_base.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_filters %}

{% block title %} {% trans 'panel message' %} {% endblock title %}

{% block content %}
    <!-- message section start -->
    <section id="msg_list" class="nav-section mb-4">
        <!-- search form start -->
        <form id="id_search_form" method="get" class="mb-4">
            <div class="row g-2">
                <div class="col-8 col-md-6 col-lg-5">
                    <input id="id_search_msg" name='q' type="text" class="textinput form-control"
                           placeholder="Enter word for search">
                </div>
                <div class="col">
                    <button class="btn-cst btn--outline-primary-cst" id="id_search_form_btn" type="button">Search
                    </button>
                </div>
            </div>
        </form>
        <!-- search form end -->

        <!-- message list start -->
        <div id="id_block_msg">
            {% include 'email_sender/_msg_sent_list.html' with msg_list=msg_list page_obj=page_obj %}
        </div>

        {% include 'email_sender/_pagination.html' with page_obj=page_obj area_label='messages' pagination_id='id_msg_pagination' %}
        <!-- message list end -->
    </section>
    <!-- message section end -->

    <!-- form send section start -->
    <section id="msg_form" class="nav-section d-none">
        <!-- form send start -->
        <h2 class="mb-3">Send Message Form</h2>
        <form action="{% url 'email_sender:msg_panel_send' %}" method="post" id="id_msg_send_form"
              enctype='multipart/form-data' class="form mb-3">
            {% csrf_token %}
            <div id="id_msg_form_errors" data-child-class="invalid-feedback d-block fw-bold rounded-4"
                 data-start-with="- " class="d-none mb-3"></div>
            {% for field in msg_record_form %}
                {% if field.name == 'recipients' %}
                    <div class="row">
                        <div class="col-12 col-sm-6">
                            {{ field|as_crispy_field }}
                            <div id="id_{{ field.name }}_feedback"></div>
                        </div>
                        <div class="col-12 col-sm-6 pt-sm-5">
                            <div class="help-text">
                                <h5 class="help-text__title">Recipient Entry Guide</h5>
                                <p class="mb-1 ps-3">
                                    <strong>Accepted Formats:</strong> Enter recipients as <code>username:email</code>
                                    (e.g., <code>john:john@example.com</code>) or simply an email (e.g., <code>test@example.com</code>).
                                </p>
                                <p class="mb-1 ps-3">
                                    <strong>Multiple Entries:</strong> Separate recipients with commas (e.g., <code>user1@example.com,
                                    user2@example.com</code>).
                                </p>
                                <p>
                                    <strong>Need to filter recipients?</strong> Use the
                                    <a type="button" class="link-primary" data-bs-toggle="modal"
                                       data-bs-target="#recipientFilterModal">
                                        Recipient Filter Form
                                    </a>
                                    to find and select specific recipients easily.
                                </p>
                            </div>

                        </div>
                    </div>
                {% else %}
                    {{ field|as_crispy_field }}
                    <div id="id_{{ field.name }}_feedback"></div>
                {% endif %}
            {% endfor %}
            <head>
                {{ msg_record_form.media }}
            </head>
            <div class="row my-4 gy-3">
                <div class="col-12 col-sm-6">
                    <div class="mb-2">
                        <p class="form-title">Message Image</p>
                    </div>
                    {{ msg_record_img_formset.management_form|crispy }}
                    {% for form in msg_record_img_formset %}
                        {% for field in form %}
                            {{ field|as_crispy_field }}
                            <div id="id_{{ form.prefix }}-{{ field.name }}_feedback"></div>
                        {% endfor %}
                    {% endfor %}
                </div>
                <div class="col-12 col-sm-6">
                    <div class="mb-2">
                        <p class="form-title">Message File</p>
                    </div>
                    {{ msg_record_file_formset.management_form|crispy }}
                    {% for form in msg_record_file_formset %}
                        {% for field in form %}
                            {{ field|as_crispy_field }}
                            <div id="id_{{ form.prefix }}-{{ field.name }}_feedback"></div>
                        {% endfor %}
                    {% endfor %}
                </div>
            </div>
            <button type="button" class="btn-cst btn--primary-cst d-flex align-items-center" id="id_msg_send_form_btn">
                <span class="spinner-border me-2 d-none" aria-hidden="true"></span>
                <span role="status">Send</span>
            </button>
        </form>
        <!-- form send end -->
    </section>
    <!-- form send section end -->

    <!-- filter recipients modal start -->
    <div class="modal fade" id="recipientFilterModal" tabindex="-1" aria-labelledby="recipientFilterModal"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header p-4">
                    <h5 class="modal-title h1">Filter Form</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body p-4">
                    <form action="{% url 'email_sender:filter_recipients' %}" method="get" id="id_recipient_form"
                          class="mb-3">
                        {{ filter_recipient_form|crispy }}
                        <button class="btn-cst btn--outline-primary-cst" type="button" id="id_recipient_form_btn">
                            enter
                        </button>
                    </form>
                    <div class="fade">
                        <p class="border rounded-4 py-2 px-3 max-h-150" id="id_recipient_result"></p>
                        <button class="btn-cst btn--primary-cst" id="id_copy_recipient_result">copy</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- filter recipients modal end -->

{% endblock content %}

{% block extra_script %}
    <script src="{% static '/js/msg_panel_script.js' %}"></script>
{% endblock extra_script %}