config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('message-panel/', include('email_sender.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

email_sender/urls.py
from django.urls import path

from . import views

app_name = 'email_sender'

urlpatterns = [
    path('', views.MessagePanelView.as_view(), name='msg_panel'),
    path('<int:pk>/', views.MessageDetailView.as_view(), name='msg_detail'),
    path('send/', views.send_and_save_mgs_view, name='msg_panel_send'),
    path('filter-recipients/', views.filter_recipients_view, name='filter_recipients'),
]

templates/_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    {% block extra_css %}
    {% endblock extra_css %}
</head>
<body>

<div class="main-container">
    <header class="main-header">
        <nav class="nav">
            <ul class="nav-menu">
                <li class="nav-item-cst mt-3 mt-md-1" data-id-target="msg_list"><a
                        href="{% url 'email_sender:msg_panel' %}"
                        class="nav-link-cst"><i
                        class="fa-solid fa-inbox"></i> messages</a></li>
                <li class="nav-item-cst" data-id-target="msg_form"><a href="{% url 'email_sender:msg_panel' %}"
                                                                      class="nav-link-cst"><i
                        class="fa-regular fa-paper-plane"></i> send message</a></li>
            </ul>
            <div class="hamburger-inside">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </div>
            <h1 class="nav-logo">Message Panel</h1>
        </nav>
    </header>


    <div class="content">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible rounded-4 p-3 w-100 w-sm-75 w-md-50 fade show"
                     role="alert">
                    <span class="sr-only">{{ message.level_tag|capfirst }}:</span> {{ message }}
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}


        {% block content %}
        {% endblock content %}
    </div>

    <aside class="aside-bar">
        <div class="hamburger-outside">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
    </aside>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block extra_script %}
{% endblock extra_script %}
</body>
</html>